#sample docker compose yaml file with mysql databsae 
version: "3"
services:
  app:
    restart: always
    image: shermanouko/app:latest
    build: . # Current directory!
    command: "gunicorn app.wsgi:application --bind 0.0.0.0:8000  --workers 2 --timeout 86400" #can add gevent and worker processes and other settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment: #can also use environemtn file directory
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_DATABASE=xxxxx
      - MYSQL_USER=xxxxx
      - MYSQL_PASSWORD=xxx

